project_id = "ilhpiarkmwdjvrfqhyhi"

[functions.evolution-webhook]
verify_jwt = false

[functions.create-vendor-user]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.notify-vendor]
verify_jwt = false
